// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRBRlMDOavxEaXVaI0qzGfl593J5uzVE',
    appId: '1:607362430124:web:4e5aa05cb541b7781a1b09',
    messagingSenderId: '607362430124',
    projectId: 'triallineapp',
    authDomain: 'triallineapp.firebaseapp.com',
    storageBucket: 'triallineapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97-XVesAYxlCy_D8X__ne0qO0E9lsUEc',
    appId: '1:968866215707:android:ef803effeeb42867cec5be',
    messagingSenderId: '968866215707',
    projectId: 'my-chat-app-e95ea',
    storageBucket: 'my-chat-app-e95ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGQP9tusnxkEsWIzQarP4hszGIeDE7Rw',
    appId: '1:607362430124:ios:96acce8d04abe1e51a1b09',
    messagingSenderId: '607362430124',
    projectId: 'triallineapp',
    storageBucket: 'triallineapp.firebasestorage.app',
    iosBundleId: 'com.example.trialLine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGQP9tusnxkEsWIzQarP4hszGIeDE7Rw',
    appId: '1:607362430124:ios:96acce8d04abe1e51a1b09',
    messagingSenderId: '607362430124',
    projectId: 'triallineapp',
    storageBucket: 'triallineapp.firebasestorage.app',
    iosBundleId: 'com.example.trialLine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcRBRlMDOavxEaXVaI0qzGfl593J5uzVE',
    appId: '1:607362430124:web:ffdefc007128fe1f1a1b09',
    messagingSenderId: '607362430124',
    projectId: 'triallineapp',
    authDomain: 'triallineapp.firebaseapp.com',
    storageBucket: 'triallineapp.firebasestorage.app',
  );
}